# Project Configuration
project:
  directories:
    instructions: "instructions"
    tasks: "instructions/tasks"
    specs: "instructions/tasks/specs"
    standards: "instructions/standards"
  files:
    requirements: "instructions/requirements.txt"
    standards: "instructions/standards.txt"
    steps: "steps.json"
  file_extensions:
    standards: ".md"
    tasks: ".md"
    specs: ".spec.json"

# Model Configuration
model:
  name: "gpt-4"
  api_key: null  # Will use ADRM_API_KEY environment variable
  temperature: 0.7

# Aider Integration Configuration
aider:
  default_files: []
  coder:
    type: "editblock"  # or "wholefile", "udiff", "architect"
    allow_edits: true
    auto_confirm: true
    include_patterns:
      - "*.py"
      - "*.js"
    exclude_patterns:
      - "*_test.py"
      - "tests/*"
  git_enabled: true
  stream_output: true
  pretty: true
  chat_history_file: ".aider.chat.history.md"

# IO Configuration
io:
  auto_confirm: true 